# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='./default.png', null=True, upload_to=''),
        ),
    ]
