# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20151222_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/var/www/boxing-api/boxing/api/static/media/default.png', upload_to=''),
        ),
    ]
