# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20151222_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
