# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20151222_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Container'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
