# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160603_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='avatar',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
