# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='related',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.Item'),
        ),
        migrations.AlterField(
            model_name='related',
            name='related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='api.Item'),
        ),
    ]
