# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160604_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='documentation',
            field=models.URLField(null=True),
        ),
    ]
