# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160604_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='is_approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
