# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20160604_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
