# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_lending_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='lending',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('refused', 'refused')], default='pending', max_length=10),
        ),
    ]
