# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160607_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='reason',
            new_name='lending_reason',
        ),
        migrations.AddField(
            model_name='lending',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lending',
            name='refusal_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lending',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('refused', 'refused'), ('returned', 'returned')], default='pending', max_length=10),
        ),
    ]
