# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20160722_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
